import pygame as p
import game_level
import game_over
import end_screen

Flags = {}

def loadFlags(dic):
    for key in dic.keys():
        Flags[key] = p.image.load("flags/" + key + ".png")

def game_loop(screen):
    dic = {
        'af': 'afghanistan',
        'al': 'albania',
        'dz': 'algeria',
        'ad': 'andorra',
        'ao': 'angola',
        'ag': 'antigua and barbuda',
        'ar': 'argentina',
        'am': 'armenia',
        'au': 'australia',
        'at': 'austria',
        'az': 'azerbaijan',
        'bs': 'bahamas',
        'bh': 'bahrain',
        'bd': 'bangladesh',
        'bb': 'barbados',
        'by': 'belarus',
        'be': 'belgium',
        'bz': 'belize',
        'bj': 'benin',
        'bt': 'bhutan',
        'bo': 'bolivia',
        'ba': 'bosnia and herzegovina',
        'bw': 'botswana',
        'br': 'brazil',
        'bn': 'brunei',
        'bg': 'bulgaria',
        'bf': 'burkina faso',
        'bi': 'burundi',
        'kh': 'cambodia',
        'cm': 'cameroon',
        'ca': 'canada',
        'cv': 'cape verde',
        'cf': 'central african republic',
        'td': 'chad',
        'cl': 'chile',
        'cn': 'china',
        'co': 'colombia',
        'km': 'comoros',
        'cg': 'republic of the congo',
        'cd': 'democratic republic of congo',
        'cr': 'costa rica',
        'ci': "côte d'ivoire",
        'hr': 'croatia',
        'cu': 'cuba',
        'cy': 'cyprus',
        'cz': 'czechia',
        'dk': 'denmark',
        'dj': 'djibouti',
        'dm': 'dominica',
        'do': 'dominican republic',
        'ec': 'ecuador',
        'eg': 'egypt',
        'sv': 'el salvador',
        'gq': 'equatorial guinea',
        'er': 'eritrea',
        'ee': 'estonia',
        'sz': 'eswatini',
        'et': 'ethiopia',
        'fj': 'fiji',
        'fi': 'finland',
        'fr': 'france',
        'ga': 'gabon',
        'gm': 'gambia',
        'ge': 'georgia',
        'de': 'germany',
        'gh': 'ghana',
        'gr': 'greece',
        'gd': 'grenada',
        'gt': 'guatemala',
        'gn': 'guinea',
        'gw': 'guinea-bissau',
        'gy': 'guyana',
        'ht': 'haiti',
        'hn': 'honduras',
        'hu': 'hungary',
        'is': 'iceland',
        'in': 'india',
        'id': 'indonesia',
        'ir': 'iran',
        'iq': 'iraq',
        'ie': 'ireland',
        'il': 'israel',
        'it': 'italy',
        'jm': 'jamaica',
        'jp': 'japan',
        'jo': 'jordan',
        'kz': 'kazakhstan',
        'ke': 'kenya',
        'ki': 'kiribati',
        'kp': 'north korea',
        'kr': 'south korea',
        'kw': 'kuwait',
        'kg': 'kyrgyzstan',
        'la': 'laos',
        'lv': 'latvia',
        'lb': 'lebanon',
        'ls': 'lesotho',
        'lr': 'liberia',
        'ly': 'libya',
        'li': 'liechtenstein',
        'lt': 'lithuania',
        'lu': 'luxembourg',
        'mg': 'madagascar',
        'mw': 'malawi',
        'my': 'malaysia',
        'mv': 'maldives',
        'ml': 'mali',
        'mt': 'malta',
        'mh': 'marshall islands',
        'mr': 'mauritania',
        'mu': 'mauritius',
        'mx': 'mexico',
        'fm': 'micronesia',
        'md': 'moldova',
        'mc': 'monaco',
        'mn': 'mongolia',
        'me': 'montenegro',
        'ma': 'morocco',
        'mz': 'mozambique',
        'mm': 'myanmar',
        'na': 'namibia',
        'nr': 'nauru',
        'np': 'nepal',
        'nl': 'netherlands',
        'nz': 'new zealand',
        'ni': 'nicaragua',
        'ne': 'niger',
        'ng': 'nigeria',
        'mk': 'north macedonia',
        'no': 'norway',
        'om': 'oman',
        'pk': 'pakistan',
        'pw': 'palau',
        'ps': 'palestine',
        'pa': 'panama',
        'pg': 'papua new guinea',
        'py': 'paraguay',
        'pe': 'peru',
        'ph': 'philippines',
        'pl': 'poland',
        'pt': 'portugal',
        'qa': 'qatar',
        'ro': 'romania',
        'ru': 'russia',
        'rw': 'rwanda',
        'kn': 'saint kitts and nevis',
        'lc': 'saint lucia',
        'vc': 'saint vincent and the grenadines',
        'ws': 'samoa',
        'sm': 'san marino',
        'st': 'são tomé and príncipe',
        'sa': 'saudi arabia',
        'sn': 'senegal',
        'rs': 'serbia',
        'sc': 'seychelles',
        'sl': 'sierra leone',
        'sg': 'singapore',
        'sk': 'slovakia',
        'si': 'slovenia',
        'sb': 'solomon islands',
        'so': 'somalia',
        'za': 'south africa',
        'ss': 'south sudan',
        'es': 'spain',
        'lk': 'sri lanka',
        'sd': 'sudan',
        'sr': 'suriname',
        'se': 'sweden',
        'ch': 'switzerland',
        'sy': 'syria',
        'tj': 'tajikistan',
        'tz': 'tanzania',
        'th': 'thailand',
        'tl': 'timor-leste',
        'tg': 'togo',
        'to': 'tonga',
        'tt': 'trinidad and tobago',
        'tn': 'tunisia',
        'tr': 'turkey',
        'tm': 'turkmenistan',
        'tv': 'tuvalu',
        'ug': 'uganda',
        'ua': 'ukraine',
        'ae': 'united arab emirates',
        'gb': 'united kingdom',
        'us': 'united states',
        'uy': 'uruguay',
        'uz': 'uzbekistan',
        'vu': 'vanuatu',
        'va': 'vatican city',
        've': 'venezuela',
        'vn': 'vietnam',
        'ye': 'yemen',
        'zm': 'zambia',
        'zw': 'zimbabwe'}
    loadFlags(dic)

    #Initializing Score and Lives
    score = 0
    lives = 3

    for key,value in dic.items():
        score,lives = game_level.game_level(screen,score,lives,Flags[key],value)
        if lives == 0:
            game_over.game_over(screen,score)
            p.quit()
        elif score == -2:
            p.quit()

    end_screen.end_screen(screen,score)